### ISSUE TITLE
加载插件的时候出现如下报错

### ISSUE THREAD

**Issue by lclbm** [pcrbot/Destiny2#1]
```
[2021-02-23 16:23:42,327 nonebot] ERROR: Failed to import "hoshino.modules.destiny2.countdown", error: type object 'destiny2_config' has no attribute 'MANIFEST_HASHES'
[2021-02-23 16:23:42,327 nonebot] ERROR: type object 'destiny2_config' has no attribute 'MANIFEST_HASHES'
Traceback (most recent call last):
  File "E:\pyhton\lib\site-packages\nonebot\plugin.py", line 249, in load_plugin
    module = importlib.import_module(module_path)
  File "E:\pyhton\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\qwe61\Documents\HoshinoBot\hoshino\modules\destiny2\__init__.py", line 1, in <module>
    from .D2_Manifest import *
  File "C:\Users\qwe61\Documents\HoshinoBot\hoshino\modules\destiny2\D2_Manifest.py", line 15, in <module>
    hashes = config.MANIFEST_HASHES
AttributeError: type object 'destiny2_config' has no attribute 'MANIFEST_HASHES'
[2021-02-23 16:23:42,330 nonebot] ERROR: Failed to import "hoshino.modules.destiny2.D2_API", error: type object 'destiny2_config' has no attribute 'MANIFEST_HASHES'
[2021-02-23 16:23:42,330 nonebot] ERROR: type object 'destiny2_config' has no attribute 'MANIFEST_HASHES'
```

**Comment by xhl6666** [comment]
已经更新新版config
